create extension if not exists "pgcrypto";
create extension if not exists "pg_net";
create extension pg_cron with schema pg_catalog;
grant usage on schema cron to postgres;
grant all privileges on all tables in schema cron to postgres;

create schema if not exists private;
grant usage on schema private to anon, authenticated, service_role, postgres;


alter database postgres
set timezone to 'Europe/Berlin';

-- Custom types
create type public.app_permission as enum (
  'users.read',
  'users.update',
  'users.delete',
  'organizations.read',
  'organizations.create',
  'organizations.update',
  'organizations.delete',
  'organizations_stripe_accounts.read',
  'organizations_stripe_accounts.create',
  'organizations_stripe_accounts.update',
  'organization_members.read',
  'organization_members.create',
  'organization_members.update',
  'organization_members.delete',
  'organization_invitations.read',
  'organization_invitations.create',
  'organization_invitations.update',
  'organization_invitations.delete',
  'students.read',
  'students.create',
  'students.update',
  'students.delete',
  'students_registration_requests.read',
  'students_registration_requests.create',
  'students_registration_requests.update',
  'students_registration_requests.delete',
  'courses.read',
  'courses.create',
  'courses.update',
  'courses.delete',
  'course_subscriptions.read',
  'course_subscriptions.create',
  'course_subscriptions.update',
  'course_subscriptions.delete',
  'course_activities.read',
  'course_activities.create',
  'course_activities.update',
  'course_activities.delete',
  'course_activity_schedules.read',
  'course_activity_schedules.create',
  'course_activity_schedules.update',
  'course_activity_schedules.delete',
  'course_subscription_bills.read',
  'course_subscription_bills.create',
  'course_subscription_bills.update',
  'course_subscription_bills.delete'
);
create type public.app_role as enum ('owner','manager', 'teacher', 'student' );
create type public.user_status as enum ('ONLINE', 'OFFLINE');
create type public.activity_types as enum ('THEORY', 'PRACTICE', 'EXAM', 'OTHER');
create type public.schedule_type as enum ('ONCE', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY');
create type public.schedule_status as enum ('PLANNED', 'COMPLETED', 'CANCELED');

-- enum for führerscheinklassen
create type public.course_type as enum ('AM', 'A1', 'A2', 'A', 'B', 'BE', 'C1', 'C1E', 'C', 'CE', 'D1', 'D1E', 'D', 'DE', 'L', 'T');

-- Notifications Types
create type public.notification_type as enum (
  'students_registration_requests.created',
  'course_subscriptions.created',
  'course_activity_schedules.updated',
  'course_activity_schedules.assigned',
  'course_subscription_bills.ready_to_pay',
  'course_subscription_bills.updated',
  'course_subscription_bills.paid',
  'course_subscription_bills.canceled'
);



-- ROLE PERMISSIONS
create table public.role_permissions (
  id           bigint generated by default as identity primary key,
  role         app_role not null,
  permission   app_permission not null,
  unique (role, permission)
);
comment on table public.role_permissions is 'Application permissions for each role.';
alter table public.role_permissions enable row level security;

-- COURSE ACTIVITY TYPES
create table public.course_activity_types (
  id           bigint generated by default as identity primary key,
  type         activity_types unique not null
);

-- USERS
create table public.users (
  id          uuid references auth.users on delete cascade not null primary key, -- UUID from auth.users
  email       text not null unique,
  firstname    text,
  lastname    text,
  fullname    text generated always as (coalesce(firstname, '') || ' ' || coalesce(lastname, '')) stored,
  avatar_path  text,
  status      user_status default 'OFFLINE'::public.user_status,
  tutorial_data jsonb default '[]'::jsonb
);
comment on table public.users is 'Profile data for each user.';
comment on column public.users.id is 'References the internal Supabase Auth user.';
alter table public.users enable row level security;
revoke update on table public.users from authenticated, anon;
grant update (firstname, lastname, avatar_path, tutorial_data) on table public.users to authenticated;


-- ORGANIZATIONS
create table public.organizations (
  id            uuid default uuid_generate_v4() primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  -- handle        text not null unique check (handle ~ '^[a-z0-9_]+$'),
  avatar_path    text,
  name          text not null,
  description       text,
  email         text,
  phone_number    text,
  website       text,
  allow_self_registration  boolean default true not null,
  preferred_language    text default 'de' not null,
  address_street  text,
  address_zip    text,
  address_city  text,
  address_country text,
  owner_id      uuid references public.users not null
);
comment on table public.organizations is 'organization data.';
alter table public.organizations enable row level security;
revoke update on table public.organizations from authenticated, anon;
grant update (name, description, avatar_path, email, phone_number, website, address_street, address_zip, address_city, address_country, preferred_language, allow_self_registration) on table public.organizations to authenticated;

-- ORGANIZATIONS STRIPE ACCOUNTS
create table public.organizations_stripe_accounts (
  id            uuid references public.organizations on delete restrict not null primary key,
  stripe_account_id  text not null,
  payment_methods    jsonb
);
comment on table public.organizations_stripe_accounts is 'Stripe account data for each organization.';
alter table public.organizations_stripe_accounts enable row level security;
revoke update on table public.organizations_stripe_accounts from authenticated, anon;
grant update (payment_methods) on table public.organizations_stripe_accounts to authenticated;


-- ORGANIZATIONS INVITATIONS
create table public.organizations_invitations (
  id            uuid default uuid_generate_v4() primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  email         text not null,
  role         app_role not null,
  organization_id    uuid references public.organizations on delete cascade not null,
  status        integer default 0 not null check (status >= 0 and status <= 2), -- 0: pending, 1: accepted, 2: rejected
  unique (email, organization_id) 
);
comment on table public.organizations_invitations is 'Invitations to join an organization.';
alter table public.organizations_invitations enable row level security;
revoke update on table public.organizations_invitations from authenticated, anon;


-- ORGANIZATION MEMBERS
create table public.organization_members (
  id            uuid default uuid_generate_v4() primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  organization_id    uuid references public.organizations on delete cascade not null,
  user_id    uuid references public.users on delete cascade not null,
  role     app_role not null,
  unique (organization_id, user_id)
);
comment on table public.organization_members is 'Members of each organization, users can be in multiple organizations.';
alter table public.organization_members enable row level security;
revoke update on table public.organization_members from authenticated, anon;
grant update (role) on table public.organization_members to authenticated;


-- STUDENTS
create table public.students (
  id          uuid default uuid_generate_v4() primary key,
  email       text not null unique,
  firstname    text not null,
  lastname    text not null,
  avatar_path    text,
  birth_date   date not null,
  phone_number  text,
  address_street  text,
  address_zip    text,
  address_city  text,
  address_country text,
  has_a_license  boolean default false not null,
  user_id      uuid references public.users,
  organization_id    uuid references public.organizations on delete cascade not null,
  created_at    timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, organization_id),
  unique (email, organization_id)
);
comment on table public.students is 'Profile data for each student.';
alter table public.students enable row level security;
revoke update on table public.students from authenticated, anon;
grant update (email, firstname, lastname, avatar_path, birth_date, phone_number, address_street, address_zip, address_city, address_country, has_a_license) on table public.students to authenticated;


-- COURSES
create table public.courses (
  id            uuid default uuid_generate_v4() primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  name          text not null,
  description       text not null,
  type         course_type not null,
  is_active     boolean default true not null,
  create_bill_on_subscription  boolean default true not null,
  allow_self_registration  boolean default true not null,
  organization_id    uuid references public.organizations on delete cascade not null,
  unique (organization_id, type)
);
comment on table public.courses is 'COURSES AVAILABLE.';
alter table public.courses enable row level security;
revoke update on table public.courses from authenticated, anon;
grant update (name, description, is_active, create_bill_on_subscription, allow_self_registration) on table public.courses to authenticated;


-- STUDENTS REGISTRATION REQUESTS
create table public.students_registration_requests (
  id            uuid default uuid_generate_v4() primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  email         text not null,
  firstname      text not null,
  lastname      text not null,
  birth_date     date not null,
  phone_number    text not null,
  address_street    text not null,
  address_zip      text not null,
  address_city    text not null,
  address_country   text not null,
  has_a_license    boolean default false not null,
  requested_course_id uuid references public.courses on delete set null,
  status        integer default 0 not null check (status >= 0 and status <= 2), -- 0: pending, 1: accepted, 2: rejected
  organization_id    uuid references public.organizations on delete cascade not null,
  unique (email, organization_id)
);
comment on table public.students_registration_requests is 'STUDENTS REGISTRATION REQUESTS.';
alter table public.students_registration_requests enable row level security;
revoke update on table public.students_registration_requests from authenticated, anon;
grant update (status) on table public.students_registration_requests to authenticated;


-- COURSE DOCUMENTS
create table public.course_documents (
  id            uuid default uuid_generate_v4() primary key,
  course_id    uuid references public.courses on delete cascade not null,
  name          text,
  description   text,
  path         text not null,
  created_at    timestamp with time zone default timezone('utc'::text, now()) not null,
  last_modified_at  timestamp with time zone default timezone('utc'::text, now()) not null,
  organization_id    uuid references public.organizations on delete cascade not null
);
comment on table public.course_documents is 'COURSE DOCUMENTS MADE AVAILABLE FOR STUDENTS.';
alter table public.course_documents enable row level security;
revoke update on table public.course_documents from authenticated, anon;
grant update (name, description, path) on table public.course_documents to authenticated;

-- COURSE REQUIRED DOCUMENTS
create table public.course_required_documents (
  id            uuid default uuid_generate_v4() primary key,
  course_id    uuid references public.courses on delete cascade not null,
  name          text not null,
  name_slug     text generated always as (replace(lower(name), ' ', '_')) stored,
  description   text not null,
  organization_id    uuid references public.organizations on delete cascade not null
);
comment on table public.course_required_documents is 'COURSE REQUIRED DOCUMENTS.';
alter table public.course_required_documents enable row level security;
revoke update on table public.course_required_documents from authenticated, anon;
grant update (name, description) on table public.course_required_documents to authenticated;


-- COURSES SUBSCRIPTIONS
create table public.course_subscriptions (
  id            uuid default uuid_generate_v4() primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  course_id    uuid references public.courses on delete cascade not null,
  student_id    uuid references public.students on delete cascade not null,
  archived_at   timestamp with time zone default null,
  organization_id    uuid references public.organizations on delete cascade not null,
  costs        numeric default 0 not null check (costs >= 0), -- The sum of all the bills
  unique (course_id, student_id) -- unique constraint to prevent multiple subscriptions for the same course and student
);
comment on table public.course_subscriptions is 'COURSES AVAILABLE.';
alter table public.course_subscriptions enable row level security;
revoke update on table public.course_subscriptions from authenticated, anon;
grant update (archived_at, costs) on table public.course_subscriptions to authenticated;
-- unique constraint to prevent multiple active subscriptions for the same course and student
-- create unique index on public.course_subscriptions (course_id, student_id) where archived_at is null;


-- COURSE SUBSCRIPTION DOCUMENTS
create table public.course_subscription_documents (
  id            uuid default uuid_generate_v4() primary key,
  course_subscription_id    uuid references public.course_subscriptions on delete cascade not null,
  required_document_id  uuid references public.course_required_documents on delete set null,
  path         text not null,
  created_at    timestamp with time zone default timezone('utc'::text, now()) not null,
  organization_id    uuid references public.organizations on delete cascade not null
);
comment on table public.course_subscription_documents is 'COURSE SUBSCRIPTION DOCUMENTS.';
alter table public.course_subscription_documents enable row level security;
revoke update on table public.course_subscription_documents from authenticated, anon;
grant update (path) on table public.course_subscription_documents to authenticated;


-- COURSE ACTIVITIES
create table public.course_activities (
  id            uuid default uuid_generate_v4() primary key,
  course_id    uuid references public.courses on delete cascade not null,
  name          text not null,
  description   text not null,
  activity_type  integer references public.course_activity_types not null,
  required     integer default 0 not null check (required >= 0),
  price        numeric default 0 not null check (price >= 0),
  sorting_order  integer default 0 not null check (sorting_order >= 0),
  organization_id    uuid references public.organizations on delete cascade not null,
  unique (course_id, sorting_order)
);
comment on table public.course_activities is 'COURSE ACTIVITIES.';
alter table public.course_activities enable row level security;
revoke update on table public.course_activities from authenticated, anon;
grant update (name, description, activity_type, required, price, sorting_order) on table public.course_activities to authenticated;


-- COURSE ACTIVITY SCHEDULES
create table public.course_activity_schedules (
  id            uuid default uuid_generate_v4() primary key,
  course_id    uuid references public.courses on delete cascade not null,
  activity_id    uuid references public.course_activities on delete cascade not null,
  assigned_to   uuid references public.users on delete set null,
  organization_id    uuid references public.organizations on delete cascade not null,
  status        public.schedule_status default 'PLANNED'::public.schedule_status not null,
  start_at     timestamp with time zone not null,
  end_at       timestamp with time zone not null,
  attendees     uuid[] default '{}'::uuid[] not null -- should be an array of unique student ids
);
comment on table public.course_activity_schedules is 'ACTIVITY SCHEDULES.';
alter table public.course_activity_schedules enable row level security;
revoke update on table public.course_activity_schedules from authenticated, anon;
grant update (assigned_to, status, start_at, end_at, attendees) on table public.course_activity_schedules to authenticated;


-- COURSE SUBSCRIPTION BILLS
create table public.course_subscription_bills (
  id            uuid default uuid_generate_v4() primary key,
  course_subscription_id    uuid references public.course_subscriptions on delete cascade not null,
  total        numeric default 0 not null check (total >= 0),
  created_at    timestamp with time zone default timezone('utc'::text, now()) not null,
  paid_at       timestamp with time zone default null,
  ready_to_pay  boolean default false not null, -- if the bill is ready to be paid, the bill is should be locked
  stripe_payment_intent_id  text, -- Stripe Payment Intent ID
  canceled_at   timestamp with time zone default null,
  organization_id    uuid references public.organizations on delete cascade not null,
  check ((paid_at is not null and canceled_at is null) or (paid_at is null and canceled_at is not null) or (paid_at is null and canceled_at is null))
);
comment on table public.course_subscription_bills is 'COURSE SUBSCRIPTION BILLS.';
alter table public.course_subscription_bills enable row level security;
revoke update on table public.course_subscription_bills from authenticated, anon;
grant update (paid_at, ready_to_pay, stripe_payment_intent_id, canceled_at, total) on table public.course_subscription_bills to authenticated;

-- COURSE SUBSCRIPTION BILL ITEMS
create table public.course_subscription_bill_items (
  id            uuid default uuid_generate_v4() primary key,
  bill_id      uuid references public.course_subscription_bills on delete set null,
  course_activity_id    uuid references public.course_activities on delete set null,
  course_activity_schedule_id    uuid references public.course_activity_schedules on delete set null,
  course_subscription_id    uuid references public.course_subscriptions on delete cascade not null,
  description   text not null,
  price       numeric default 0 not null check (price >= 0),
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  organization_id    uuid references public.organizations on delete cascade not null,
  unique (bill_id, course_activity_id, course_activity_schedule_id, course_subscription_id)
);
comment on table public.course_subscription_bill_items is 'COURSE SUBSCRIPTION BILL ITEMS.';
alter table public.course_subscription_bill_items enable row level security;
revoke update on table public.course_subscription_bill_items from authenticated, anon;
grant update (bill_id, course_activity_schedule_id) on table public.course_subscription_bill_items to authenticated;

-- Bill History Action type
create type public.bill_history_action_type as enum ('ITEM_ADDED', 'ITEM_REMOVED', 'ITEM_UPDATED', 'BILL_READY_TO_PAY', 'BILL_PAID');

-- COURSE SUBSCRIPTION BILL HISTORY
create table public.course_subscription_bill_history (
  id            uuid default uuid_generate_v4() primary key,
  bill_id      uuid references public.course_subscription_bills on delete cascade not null,
  actor_id      uuid references public.users on delete set null,
  activity      public.bill_history_action_type not null,
  item_description  text not null,
  item_price    numeric not null check (item_price >= 0),
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  organization_id    uuid references public.organizations on delete cascade not null
);
comment on table public.course_subscription_bill_history is 'COURSE SUBSCRIPTION BILL HISTORY.';
alter table public.course_subscription_bill_history enable row level security;
revoke update on table public.course_subscription_bill_history from authenticated, anon;


-- Notifications
create table public.notifications (
  id            uuid default uuid_generate_v4() primary key,
  actor_id      uuid references public.users on delete set null,
  type          public.notification_type not null,
  target_roles   public.app_role[] default '{}'::public.app_role[] not null,
  target_id       uuid,
  date          timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at    timestamp with time zone default timezone('utc'::text, now()) not null,
  resource_id    uuid,
  payload      jsonb,
  organization_id    uuid references public.organizations on delete set null
);
comment on table public.notifications is 'Notifications for each user.';
alter table public.notifications enable row level security;
revoke update on table public.notifications from authenticated, anon;
grant update (updated_at) on table public.notifications to authenticated;


-- Notifications Read Status
create table public.notifications_read_status (
  id            uuid default uuid_generate_v4() primary key,
  notification_id    uuid references public.notifications on delete cascade not null,
  user_id       uuid references public.users on delete cascade not null,
  read_at       timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (notification_id, user_id)
);
comment on table public.notifications_read_status is 'Notifications read status for each user.';
alter table public.notifications_read_status enable row level security;
revoke update on table public.notifications_read_status from authenticated, anon;
grant update (read_at) on table public.notifications_read_status to authenticated;


-- VIEWS
-- Organization Members View
create or replace view public.organization_members_view as
select
  organization_members.id,
  organization_members.inserted_at,
  organization_members.organization_id,
  organization_members.user_id,
  organization_members.role,
  users.email as user_email,
  users.firstname as user_firstname,
  users.lastname as user_lastname,
  users.fullname as user_fullname,
  users.avatar_path as user_avatar_path
from public.organization_members
inner join public.organizations on organization_members.organization_id = organizations.id
inner join public.users on organization_members.user_id = users.id;

-- Student & Subscriptions count View
create or replace view public.students_view as
select
  students.id,
  students.email,
  students.firstname,
  students.lastname,
  students.avatar_path,
  students.birth_date,
  students.phone_number,
  students.address_street,
  students.address_zip,
  students.address_city,
  students.address_country,
  students.has_a_license,
  students.organization_id,
  students.created_at,
  subscriptions as subscriptions_count
from public.students
left join (
  select
    student_id,
    count(*) as subscriptions
  from public.course_subscriptions where archived_at is null
  group by student_id
) as subscriptions on students.id = subscriptions.student_id;


-- Bills View with Course, Subscription and Student
create or replace view public.course_subscription_bills_view as
select
  course_subscription_bills.id,
  course_subscription_bills.course_subscription_id,
  course_subscription_bills.total,
  course_subscription_bills.created_at,
  course_subscription_bills.paid_at,
  course_subscription_bills.canceled_at,
  course_subscription_bills.ready_to_pay,
  course_subscription_bills.stripe_payment_intent_id,
  course_subscription_bills.organization_id,
  course_subscriptions.course_id,
  course_subscriptions.student_id,
  courses.name as course_name,
  courses.description as course_description,
  students.email as student_email,
  students.firstname as student_firstname,
  students.lastname as student_lastname
from public.course_subscription_bills
inner join public.course_subscriptions on course_subscription_bills.course_subscription_id = course_subscriptions.id
inner join public.courses on course_subscriptions.course_id = courses.id
inner join public.students on course_subscriptions.student_id = students.id;

-- Bill Items View grouped by course_activity_id
create or replace view public.course_subscription_bill_items_view as
select
  course_activity.name as activity_name,
  course_activity.description as activity_description,
  bill_id,
  array_agg(bill_items) as items,
  sum(bill_items.price) as total
from public.course_subscription_bill_items as bill_items
left join public.course_activities as course_activity on bill_items.course_activity_id = course_activity.id
group by course_activity_id, activity_name, activity_description, bill_id;


-- Organisation Public View - Joining with courses as array
create or replace view public.organizations_view as
select
  organizations.id,
  organizations.name,
  organizations.description,
  organizations.avatar_path,
  organizations.email,
  organizations.phone_number,
  organizations.website,
  organizations.address_street,
  organizations.address_zip,
  organizations.address_city,
  organizations.address_country,
  organizations.owner_id,
  organizations.allow_self_registration,
  organizations.preferred_language,
  users.email as owner_email,
  users.firstname as owner_firstname,
  users.lastname as owner_lastname,
  courses as organization_courses
from public.organizations
left join (
  select
    courses.organization_id,
    jsonb_agg(jsonb_build_object(
      'id', courses.id,
      'name', courses.name,
      'description', courses.description,
      'type', courses.type,
      'is_active', courses.is_active
    )) as courses
  from public.courses
  group by courses.organization_id
) as courses on organizations.id = courses.organization_id
left join public.users on organizations.owner_id = users.id;

-- Organization's Courses Subscriptions View joining with students
create or replace view public.course_subscriptions_view as
select
  course_subscriptions.id,
  course_subscriptions.course_id,
  course_subscriptions.student_id,
  course_subscriptions.archived_at,
  course_subscriptions.costs,
  course_subscriptions.organization_id,
  courses.name as course_name,
  courses.description as course_description,
  courses.type as course_type,
  students.email as student_email,
  students.firstname as student_firstname,
  students.lastname as student_lastname,
  students.user_id as student_user_id
from public.course_subscriptions
inner join public.courses on course_subscriptions.course_id = courses.id
inner join public.students on course_subscriptions.student_id = students.id;


-- Organization's Schedules View joining with activities, group by course_id
create or replace view public.course_activity_schedules_view as
select
  course_activity_schedules.id,
  course_activity_schedules.course_id,
  course_activity_schedules.activity_id,
  course_activity_schedules.assigned_to,
  course_activity_schedules.status,
  course_activity_schedules.start_at,
  course_activity_schedules.end_at,
  course_activity_schedules.organization_id,
  course_activity_schedules.attendees,
  course_activities.name as activity_name,
  course_activities.description as activity_description,
  course_activities.activity_type,
  courses.name as course_name,
  courses.description as course_description,
  users.email as assigned_to_email,
  users.firstname as assigned_to_firstname,
  users.lastname as assigned_to_lastname,
  users.fullname as assigned_to_fullname
from public.course_activity_schedules
inner join public.course_activities on course_activity_schedules.activity_id = course_activities.id
inner join public.courses on course_activity_schedules.course_id = courses.id
left join public.users on course_activity_schedules.assigned_to = users.id;


-- Subscriptions Stats View with course name, costs, sum of bills
create or replace view public.course_subscriptions_stats_view as
select
  course_subscriptions.id,
  course_subscriptions.course_id,
  course_subscriptions.student_id,
  course_subscriptions.archived_at,
  course_subscriptions.costs,
  course_subscriptions.organization_id,
  courses.name as course_name,
  courses.description as course_description,
  sum(course_subscription_bills.total) as total_bills
from public.course_subscriptions
inner join public.courses on course_subscriptions.course_id = courses.id
left join public.course_subscription_bills on course_subscriptions.id = course_subscription_bills.course_subscription_id
and course_subscription_bills.paid_at is not null
group by course_subscriptions.id, courses.name, courses.description;


create or replace view public.notifications_view as
select
  notifications.id,
  notifications.actor_id,
  notifications.type,
  notifications.target_roles,
  notifications.target_id,
  notifications.date,
  notifications.updated_at,
  notifications.resource_id,
  notifications.organization_id,
  notifications.payload,
  users.email as actor_email,
  users.firstname as actor_firstname,
  users.lastname as actor_lastname,
  users.fullname as actor_fullname,
  notifications_read_status.read_at as read_at
from public.notifications
left join public.users on notifications.actor_id = users.id
left join public.notifications_read_status on notifications.id = notifications_read_status.notification_id and notifications_read_status.user_id = auth.uid();

alter view public.notifications_view set (security_invoker = true);

-- Functions

-- Add an attendee to schedule
create or replace function public.add_attendee_to_schedule(
  course_schedule_id uuid,
  course_subscription_id uuid
)
returns boolean as $$
declare
  schedule_attendees uuid[];
begin

  select attendees into schedule_attendees from public.course_activity_schedules where id = course_schedule_id;

  -- Check if the subscription is active
  if not public.is_subscription_active(course_subscription_id) then
    raise exception 'Subscription is not active';
  end if;

  -- Check if the course_subscription_id is already in the attendees
  if course_subscription_id = any(schedule_attendees) then
    raise exception 'Subscription is already in the attendees';
  end if;

  -- Check if the schedule is active
  if not public.is_schedule_active(course_schedule_id) then
    raise exception 'Schedule is not active';
  end if;

  update public.course_activity_schedules
  set attendees = array_append(attendees, course_subscription_id)
  where id = course_schedule_id;

  return true;
end;
$$ language plpgsql security invoker set search_path = public;

-- Remove an attendee from schedule
create or replace function public.remove_attendee_from_schedule(
  course_schedule_id uuid,
  course_subscription_id uuid
)
returns boolean as $$
declare
  schedule_attendees uuid[];
begin
  select attendees into schedule_attendees from public.course_activity_schedules where id = course_schedule_id;

  -- Check if the subscription is active
  if not public.is_subscription_active(course_subscription_id) then
    raise exception 'Subscription is not active';
  end if;

  -- Check if the course_subscription_id is already in the attendees
  if not course_subscription_id = any(schedule_attendees) then
    raise exception 'Subscription is not in the attendees';
  end if;

  -- Check if the schedule is active
  if not public.is_schedule_active(course_schedule_id) then
    raise exception 'Schedule is not active';
  end if;

  update public.course_activity_schedules
  set attendees = array_remove(attendees, course_subscription_id)
  where id = course_schedule_id;

  return true;
end;
$$ language plpgsql security invoker set search_path = public;


-- Generate Bill for Subscription
create or replace function public.generate_bill_for_subscription(
  subscription_id uuid
)
returns uuid as $$
declare
  org_id uuid;
  bill_items uuid[];
  bill_total numeric;
  b_id uuid;
begin
  select organization_id into org_id from public.course_subscriptions where id = subscription_id;

  select array_agg(id) into bill_items from public.course_subscription_bill_items where course_subscription_id = subscription_id and bill_id is null;

  if array_length(bill_items, 1) > 0 then
    select sum(price) into bill_total from public.course_subscription_bill_items where id = any(bill_items);

    insert into public.course_subscription_bills (course_subscription_id, organization_id, total)
    values (subscription_id, org_id, bill_total)
    returning id into b_id;

    update public.course_subscription_bill_items set bill_id = b_id
    where id = any(bill_items);

    return b_id;
  end if;

  return null;
end;
$$ language plpgsql security invoker set search_path = public;

-- Generate Bill for Subscriptions
create or replace function public.generate_bill_for_subscriptions()
returns void as $$
declare
  subscriptions uuid[];
  subscription_id uuid;
begin
  select array_agg(id) into subscriptions from public.course_subscriptions where archived_at is null;

  foreach subscription_id in array subscriptions loop
    perform public.generate_bill_for_subscription(subscription_id);
  end loop;
end;
$$ language plpgsql security invoker set search_path = public;

-- Helpers Functions

-- Authorize function
create or replace function public.authorize(
  requested_permission app_permission,
  org_id uuid
)
returns boolean as $$
declare
  bind_permissions int;
  user_role public.app_role;
  owner uuid;
begin

  select owner_id into owner from public.organizations where id = org_id;

  --check if the user is the main owner
  if owner = auth.uid() then
    return true;
  end if;

  -- Fetch user role once and store it to reduce number of calls
  select role into user_role from public.organization_members where organization_id = org_id and user_id = auth.uid() limit 1;

  if user_role is null then
    return false;
  end if;

  select count(*)
  into bind_permissions
  from public.role_permissions
  where role_permissions.permission = requested_permission
    and role_permissions.role = user_role;

  return bind_permissions > 0;
end;
$$ language plpgsql security definer set search_path = public;


create or replace function is_main_owner(
  org_id uuid
)
returns boolean as $$
declare
  owner uuid;
begin
  select owner_id into owner from public.organizations where id = org_id;

  return owner = auth.uid();
end;
$$ language plpgsql security definer set search_path = public;

-- 2 users are in the same organization
create or replace function public.are_users_in_same_organization(
  user_id_1 uuid,
  user_id_2 uuid
)
returns boolean as $$
declare
  org_id_1 uuid;
  org_id_2 uuid;
begin

  return exists (select 1 from organization_members member_1 join organization_members member_2 on member_1.organization_id = member_2.organization_id
  where member_1.user_id = user_id_1 and member_2.user_id = user_id_2); 
end;
$$ language plpgsql security definer set search_path = public;


-- check if a subscription is active / not archived
create or replace function public.is_subscription_active(
  subscription_id uuid
)
returns boolean as $$
declare
  archived_date timestamp with time zone;
begin
  select archived_at into archived_date from public.course_subscriptions where id = subscription_id;

  if archived_date is not null then
    return false;
  end if;

  return true;
end;
$$ language plpgsql security definer set search_path = public;

-- check if schedule is COMPLETED or CANCELED
create or replace function public.is_schedule_active(
  schedule_id uuid
)
returns boolean as $$
declare s_status public.schedule_status;
begin
  select status into s_status from public.course_activity_schedules where id = schedule_id;
  if s_status = 'COMPLETED' or s_status = 'CANCELED' then
    return false;
  end if;
  return true;
end;
$$ language plpgsql security definer set search_path = public;


-- check if a bill can be updated
create or replace function public.can_update_bill(
  bill_id uuid
)
returns boolean as $$
declare
  is_paid boolean;
  is_ready_to_pay boolean;
  is_canceled boolean;
begin

  select paid_at is not null, ready_to_pay, canceled_at is not null into is_paid, is_ready_to_pay, is_canceled from public.course_subscription_bills where id = bill_id;

  return is_paid = false or is_ready_to_pay = false or is_canceled = false;
end;
$$ language plpgsql security definer set search_path = public;

-- check if a user is targeted by a notification
create or replace function public.is_user_targeted_by_notification(
  notification_id uuid,
  org_id uuid
)
returns boolean as $$
declare
  user_role public.app_role;
  n_target_roles public.app_role[];
  n_target_id uuid;
begin
  select role into user_role from public.organization_members where organization_id = org_id and user_id = auth.uid() limit 1;
  select target_roles, target_id into n_target_roles, n_target_id from public.notifications where id = notification_id;

  -- Check if the user has the right role in the Organization
  if user_role is null then
    return false;
  end if;

  -- Check if the user is the target_id of the notification
  if n_target_id = auth.uid() then
    return true;
  end if;

  -- if user_role is included in the target_roles, return true
  if user_role = any(n_target_roles) then
    return true;
  end if;

  return false;
end;
$$ language plpgsql security definer set search_path = public;


-- TRIGGERS
create function public.handle_new_user() 
returns trigger as $$
declare org_id uuid;
declare role_name public.app_role;
begin
  insert into public.users (id, email)
  values (new.id, new.email);

  return new;
end;
$$ language plpgsql security definer set search_path = auth, public;
-- trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


create or replace function public.handle_new_organization() 
returns trigger as $$
declare org_id uuid;
begin

  insert into public.organization_members (organization_id, user_id, role)
  values (new.id, new.owner_id, 'owner');

  return new;
end;
$$ language plpgsql security invoker set search_path = public;
-- trigger the function every time a Org is created
create trigger on_org_created
  after insert on public.organizations
  for each row execute procedure public.handle_new_organization();


create or replace function public.handle_new_course()
returns trigger as $$
declare org_id uuid;
begin
  org_id := new.organization_id;

  -- Todo: May be usefull later

  return new;
end;
$$ language plpgsql security invoker set search_path = public;
-- trigger the function every time a course is created
create trigger on_course_created
  after insert on public.courses
  for each row execute procedure public.handle_new_course();


-- handle New Registration Request
create or replace function public.handle_new_registration_request()
returns trigger as $$
declare org_id uuid;
begin
  --   -- Send Notification to the student
  -- perform private.send_notification(
  --   auth.uid(),
  --   'students_registration_requests.created',
  --   '{owner, manager, teacher}'::public.app_role[],
  --   null,
  --   new.id,
  --   to_jsonb(new),
  --   new.organization_id
  -- );

  return new;
end;
$$ language plpgsql security invoker set search_path = public, private;
-- trigger the function every time a registration request is created
create trigger on_registration_request_created
  after insert on public.students_registration_requests
  for each row execute procedure public.handle_new_registration_request();

-- handle Registration Request confirmation
create or replace function public.handle_registration_request_confirmation()
returns trigger as $$
declare org_id uuid;
declare student_id uuid;
begin
  org_id := new.organization_id;

  -- prevent updating the status to PENDING
  if new.status = 0 then
    raise exception 'Status cannot be set to PENDING';
  end if;

  -- if the status is ACCEPTED, insert the student
  if new.status = 1 then
    insert into public.students (email, firstname, lastname, birth_date, phone_number, address_street, address_zip, address_city, address_country, has_a_license, organization_id)
    values (new.email, new.firstname, new.lastname, new.birth_date, new.phone_number, new.address_street, new.address_zip, new.address_city, new.address_country, new.has_a_license, org_id)
    returning id into student_id;

    -- add the student to the wished course
    insert into public.course_subscriptions (course_id, student_id, organization_id)
    values (new.requested_course_id, student_id, org_id);
  end if;

  return new;
end;
$$ language plpgsql security invoker set search_path = public;
-- trigger the function every time a registration request is updated
create trigger on_registration_request_updated
  after update of status on public.students_registration_requests
  for each row execute procedure public.handle_registration_request_confirmation();


-- Handle New Invitations
create or replace function public.handle_new_invitation()
returns trigger as $$
declare
  payload jsonb;
  invited_user_id uuid;
begin

  -- check if user already exists
  select id into invited_user_id from public.users where email = new.email;

  -- if user exist, check if the user is already a member of the organization
  if invited_user_id is not null then
    if exists (select 1 from public.organization_members where user_id = invited_user_id and organization_id = new.organization_id) then
      raise exception 'User is already a member of the organization';
    end if;
  end if;

  return new;

end;
$$ language plpgsql security invoker set search_path = public;
create or replace trigger new_invitation_webhook
  after insert on public.organizations_invitations
  for each row execute function public.handle_new_invitation();

-- handle new course subscription
create or replace function public.handle_new_course_subscription()
returns trigger as $$
declare org_id uuid;
declare is_course_active boolean;
declare create_bill boolean;
declare bill_id uuid;
declare activity public.course_activities;
declare n_payload jsonb;
begin
  org_id := new.organization_id;
  select is_active, create_bill_on_subscription into is_course_active, create_bill from public.courses where id = new.course_id;

  -- check if Student Belong to the Organization
  if not exists (select 1 from public.students where id = new.student_id and organization_id = org_id) then
    raise exception 'Student does not belong to the organization';
  end if;

  -- if the course is not active, raise an exception
  if not is_course_active then
    raise exception 'Course is not active';
  end if;

  -- if the bill should be created, create a new bill and insert default items based on the course activities and required count
  if create_bill then

    -- loop over the course activities and insert the required number of items
    for activity in (select * from public.course_activities where course_id = new.course_id) loop
      if activity.required > 0 then
        for i in 1..activity.required loop
          insert into public.course_subscription_bill_items (course_activity_id, description, price, organization_id, course_subscription_id)
          values (activity.id, activity.name, activity.price, org_id, new.id);
        end loop;
      end if;
    end loop;
  end if;

  return new;
end;
$$ language plpgsql security invoker set search_path = public, private;
-- trigger the function every time a course subscription is created
create trigger on_course_subscription_created
  after insert on public.course_subscriptions
  for each row execute procedure public.handle_new_course_subscription();

-- handle archive course subscription
create or replace function public.handle_archive_course_subscription()
returns trigger as $$
begin

  -- check if the subscription is already archived
  if new.archived_at is not null then
    raise exception 'Subscription is already archived';
  end if;

  -- find the course subscription bills that are not paid or canceled
  if exists (select 1 from public.course_subscription_bills where course_subscription_id = new.id and (paid_at is null and canceled_at is null)) then
    raise exception 'Subscription has unpaid bills';
  end if;

  return new;
end;
$$ language plpgsql security invoker set search_path = public;
-- trigger the function every time a course subscription is updated
create trigger on_course_subscription_updated
  after update of archived_at on public.course_subscriptions
  for each row execute procedure public.handle_archive_course_subscription();


-- handle update update schedule status
create or replace function public.handle_update_schedule_status()
returns trigger as $$
declare
  course_activity_id uuid;
  course_activity_name text;
  course_activity_price numeric;
begin
  -- If Schedule ist Completed, generate Attendances for all attendees
  if new.status = 'COMPLETED' then
    -- get the course activity id, name and price
    select id, name, price into course_activity_id, course_activity_name, course_activity_price from public.course_activities where id = new.activity_id;
    -- loop over the attendees and insert a new bill item for each one
    for i in 1..array_length(new.attendees, 1) loop
      -- check if the subscription is active
      if public.is_subscription_active(new.attendees[i]) then
        -- insert a new bill item for each attendee
        insert into public.course_subscription_bill_items (course_activity_id, course_activity_schedule_id, course_subscription_id, description, price, organization_id)
        values (course_activity_id, new.id, new.attendees[i], course_activity_name, course_activity_price, new.organization_id);
      end if;

    end loop;
  end if;

  return new;
end;
$$ language plpgsql security invoker set search_path = public;
-- trigger the function every time a course activity schedule status is updated
create trigger on_course_activity_schedule_updated
  after update of status on public.course_activity_schedules
  for each row execute procedure public.handle_update_schedule_status();

-- handle new bill item
create or replace function public.handle_new_bill_item()
returns trigger as $$
begin
  -- check if a bill_id is already set
  if new.bill_id is not null then
    -- check if the linked bill can be updated
    if not public.can_update_bill(new.bill_id) then
      raise exception 'Bill cannot be updated';
    end if;

    -- if the bill can be updated, update the bill with the new item
    update public.course_subscription_bills
    set total = total + new.price
    where id = new.bill_id;

    -- insert a new bill history item
    insert into public.course_subscription_bill_history (bill_id, actor_id, activity, item_description, item_price, organization_id)
    values (new.bill_id, auth.uid(), 'ITEM_ADDED', new.description, new.price, new.organization_id);
  end if;
  return new;
end;
$$ language plpgsql security invoker set search_path = public;
-- trigger the function every time a course subscription bill item is created
create trigger on_course_subscription_bill_item_created
  after insert on public.course_subscription_bill_items
  for each row execute procedure public.handle_new_bill_item();

-- public.handle remove bill item
create or replace function public.handle_remove_bill_item()
returns trigger as $$
begin
  -- check if a bill_id is already set
  if new.bill_id is not null then
    -- check if the linked bill can be updated
    if not public.can_update_bill(new.bill_id) then
      raise exception 'Bill cannot be updated';
    end if;

    -- if the bill can be updated, update the bill with the new item
    update public.course_subscription_bills
    set total = total - new.price
    where id = new.bill_id;

    -- insert a new bill history item
    insert into public.course_subscription_bill_history (bill_id, actor_id, activity, item_description, item_price, organization_id)
    values (new.bill_id, auth.uid(), 'ITEM_REMOVED', new.description, new.price, new.organization_id);
  end if;
  return new;
end;
$$ language plpgsql security invoker set search_path = public;
-- trigger the function every time a course subscription bill item is deleted
create trigger on_course_subscription_bill_item_deleted
  before delete on public.course_subscription_bill_items
  for each row execute procedure public.handle_remove_bill_item();











-- Policies

-- Role Permissions Policies
create policy "Everyone can see role_permissions" on public.role_permissions for select to authenticated using (true);

-- Users Policies
create policy "Users can see their own data" on public.users for select to authenticated using (auth.uid() = id);
create policy "Users can see other users in the same organization" on public.users for select to authenticated using (public.are_users_in_same_organization(auth.uid(), id));
create policy "User can see update their own data" on public.users for update to authenticated using (auth.uid() = id);


-- Organizations Policies
create policy "Everyone member can see organizations" on public.organizations for select to authenticated, anon using (public.authorize('organizations.read', id));
create policy "Owner & Manager can update organizations" on public.organizations for update to authenticated using ((auth.uid() = owner_id) or (public.authorize('organizations.update', id)));
create policy "Create organization only if owner is the same as the user who make the request" on public.organizations for insert to authenticated with check (auth.uid() = owner_id);
create policy "Owner can delete organizations" on public.organizations for delete to authenticated using (auth.uid() = owner_id);

-- Organizations Stripe Accounts Policies
create policy "Everyone in Org can see organizations_stripe_accounts" on public.organizations_stripe_accounts for select to authenticated using (public.authorize('organizations_stripe_accounts.read', id));
create policy "Main Owner can insert organizations_stripe_accounts" on public.organizations_stripe_accounts for insert to authenticated with check (public.is_main_owner(id));
create policy "Owner & Manager can update organizations_stripe_accounts" on public.organizations_stripe_accounts for update to authenticated using (public.authorize('organizations_stripe_accounts.update', id));
create policy "Owner can delete organizations_stripe_accounts" on public.organizations_stripe_accounts for delete to authenticated using (public.is_main_owner(id));

-- Organization Members Policies
create policy "Every Member can see organization_members" on public.organization_members for select to authenticated using (public.authorize('organization_members.read', organization_id));
create policy "Owner can insert organization_members" on public.organization_members for insert to authenticated with check (public.authorize('organization_members.create', organization_id) or public.is_main_owner(organization_id));
create policy "Owner can update organization_members" on public.organization_members for update to authenticated using (public.authorize('organization_members.update', organization_id));
create policy "Owner can delete organization_members" on public.organization_members for delete to authenticated using ((public.authorize('organization_members.delete', organization_id)) or (auth.uid() = user_id));

-- Organizations Invitations Policies
create policy "User can see their own organization_invitations" on public.organizations_invitations for select to authenticated using (auth.email() = email);
create policy "Owner & Manager see organization_invitations" on public.organizations_invitations for select to authenticated using (public.authorize('organization_invitations.read', organization_id));
create policy "Owner & Manager can insert organization_invitations" on public.organizations_invitations for insert to authenticated with check (public.authorize('organization_invitations.create', organization_id));
create policy "Owner & Manager can delete organization_invitations" on public.organizations_invitations for delete to authenticated using (public.authorize('organization_invitations.delete', organization_id));

-- Students Policies
create policy "Student can see their own data" on public.students for select to authenticated using (auth.uid() = user_id);
create policy "Everyone except students can see other students" on public.students for select to authenticated using (public.authorize('students.read', organization_id));
create policy "Student can insert their own data" on public.students for insert to authenticated with check (auth.uid() = user_id);
create policy "Student can update their own data" on public.students for update to authenticated using (auth.uid() = user_id);
create policy "Owner & Manager can insert students" on public.students for insert to authenticated with check (public.authorize('students.create', organization_id));
create policy "Owner & Manager can update students" on public.students for update to authenticated using (public.authorize('students.update', organization_id)) with check (public.authorize('students.update', organization_id));
create policy "Owner & Manager can delete students" on public.students for delete to authenticated using (public.authorize('students.delete', organization_id));

-- Students Registration Requests Policies
create policy "Everyone authenticated staff user can see students_registration_requests" on public.students_registration_requests for select to authenticated using (public.authorize('students_registration_requests.read', organization_id));
create policy "Insert students_registration_requests" on public.students_registration_requests for insert to authenticated, anon with check (true);
create policy "Owner & Manager can update students_registration_requests" on public.students_registration_requests for update to authenticated using (public.authorize('students_registration_requests.update', organization_id)) with check (public.authorize('students_registration_requests.update', organization_id));
create policy "Owner & Manager can delete students_registration_requests" on public.students_registration_requests for delete to authenticated using (public.authorize('students_registration_requests.delete', organization_id));

-- Courses Policies
create policy "Everyone can see courses" on public.courses for select to authenticated using (public.authorize('courses.read', organization_id));
create policy "Everyone can see courses_documents" on public.course_documents for select to authenticated using (public.authorize('courses.read', organization_id));
create policy "Everyone can see course_required_documents" on public.course_required_documents for select to authenticated using (public.authorize('courses.read', organization_id));
create policy "Owner, Manager can insert courses" on public.courses for insert to authenticated with check (public.authorize('courses.create', organization_id));
create policy "Owner, Manager can insert courses_documents" on public.course_documents for insert to authenticated with check (public.authorize('courses.create', organization_id));
create policy "Owner, Manager can insert course_required_documents" on public.course_required_documents for insert to authenticated with check (public.authorize('courses.create', organization_id));
create policy "Owner & Manager can update courses" on public.courses for update to authenticated using (public.authorize('courses.update', organization_id)) with check (public.authorize('courses.update', organization_id));
create policy "Owner & Manager can update courses_documents" on public.course_documents for update to authenticated using (public.authorize('courses.update', organization_id)) with check (public.authorize('courses.update', organization_id));
create policy "Owner & Manager can update course_required_documents" on public.course_required_documents for update to authenticated using (public.authorize('courses.update', organization_id)) with check (public.authorize('courses.update', organization_id));
create policy "Owner & Manager can delete courses" on public.courses for delete to authenticated using (public.authorize('courses.delete', organization_id));
create policy "Owner & Manager can delete courses_documents" on public.course_documents for delete to authenticated using (public.authorize('courses.delete', organization_id));
create policy "Owner & Manager can delete course_required_documents" on public.course_required_documents for delete to authenticated using (public.authorize('courses.delete', organization_id));

-- Course Subscriptions Policies
create policy "Everyone can see course_subscriptions" on public.course_subscriptions for select to authenticated using (public.authorize('course_subscriptions.read', organization_id));
create policy "Everyone can see course_subscription_documents" on public.course_subscription_documents for select to authenticated using (public.authorize('course_subscriptions.read', organization_id));

create policy "Owner, Manager can insert course_subscriptions" on public.course_subscriptions for insert to authenticated with check (public.authorize('course_subscriptions.create', organization_id));
create policy "Owner, Manager can insert course_subscription_documents" on public.course_subscription_documents for insert to authenticated with check (public.authorize('course_subscriptions.create', organization_id) and public.is_subscription_active(course_subscription_id));

create policy "Owner & Manager can update course_subscriptions" on public.course_subscriptions for update to authenticated using (public.authorize('course_subscriptions.update', organization_id)) with check (public.authorize('course_subscriptions.update', organization_id));
create policy "Owner & Manager can update course_subscription_documents" on public.course_subscription_documents for update to authenticated using (public.authorize('course_subscriptions.update', organization_id)) with check (public.authorize('course_subscriptions.update', organization_id) and public.is_subscription_active(course_subscription_id));

create policy "Owner & Manager can delete course_subscriptions" on public.course_subscriptions for delete to authenticated using (public.authorize('course_subscriptions.delete', organization_id));
create policy "Owner & Manager can delete course_subscription_documents" on public.course_subscription_documents for delete to authenticated using (public.authorize('course_subscriptions.delete', organization_id));

-- Course Activities Policies
create policy "Everyone can see course_activities" on public.course_activities for select to authenticated using (public.authorize('course_activities.read', organization_id));
create policy "Owner, Manager can insert course_activities" on public.course_activities for insert to authenticated with check (public.authorize('course_activities.create', organization_id));
create policy "Owner & Manager can update course_activities" on public.course_activities for update to authenticated using (public.authorize('course_activities.update', organization_id)) with check (public.authorize('course_activities.update', organization_id));
create policy "Owner can delete course_activities" on public.course_activities for delete to authenticated using (public.authorize('course_activities.delete', organization_id));

-- Course Activity Schedules Policies
create policy "Everyone can see course_activity_schedules" on public.course_activity_schedules for select to authenticated using (public.authorize('course_activity_schedules.read', organization_id));
create policy "Owner, Manager & Teacher can insert course_activity_schedules" on public.course_activity_schedules for insert to authenticated with check (public.authorize('course_activity_schedules.create', organization_id));
create policy "Owner, Manager & Teacher can update course_activity_schedules" on public.course_activity_schedules for update to authenticated using (public.authorize('course_activity_schedules.update', organization_id)) with check (public.authorize('course_activity_schedules.update', organization_id) and public.is_schedule_active(id));
create policy "Owner, Manger % Teacher can delete course_activity_schedules" on public.course_activity_schedules for delete to authenticated using (public.authorize('course_activity_schedules.delete', organization_id));


-- Course Subscription Bills Policies
create policy "Everyone can see course_subscription_bills" on public.course_subscription_bills for select to authenticated using (public.authorize('course_subscription_bills.read', organization_id));
create policy "Everyone can see course_subscription_bill_items" on public.course_subscription_bill_items for select to authenticated using (public.authorize('course_subscription_bills.read', organization_id));
create policy "Everyone can see course_subscription_bill_history" on public.course_subscription_bill_history for select to authenticated using (public.authorize('course_subscription_bills.read', organization_id));

create policy "Owner, Manager can insert course_subscription_bills" on public.course_subscription_bills for insert to authenticated with check (public.authorize('course_subscription_bills.create', organization_id) and public.is_subscription_active(course_subscription_id));
create policy "Owner, Manager can insert course_subscription_bill_items" on public.course_subscription_bill_items for insert to authenticated with check (public.authorize('course_subscription_bills.create', organization_id));

create policy "Owner & Manager can update course_subscription_bills" on public.course_subscription_bills for update to authenticated using (public.authorize('course_subscription_bills.update', organization_id)) with check (public.authorize('course_subscription_bills.update', organization_id) and public.can_update_bill(id));
create policy "Owner & Manager can update course_subscription_bill_items" on public.course_subscription_bill_items for update to authenticated using (public.authorize('course_subscription_bills.update', organization_id)) with check (public.authorize('course_subscription_bills.update', organization_id));

create policy "Owner can delete course_subscription_bills" on public.course_subscription_bills for delete to authenticated using (public.authorize('course_subscription_bills.delete', organization_id) );
create policy "Owner can delete course_subscription_bill_items" on public.course_subscription_bill_items for delete to authenticated using (public.authorize('course_subscription_bills.delete', organization_id));

create policy "Everyone can see course_activity_types" on public.course_activity_types for select to authenticated using (true);

create policy "Set Read if user_id matches the user" on public.notifications_read_status for insert to authenticated with check (auth.uid() = user_id);
create policy "Read read status if user_id matches the user" on public.notifications_read_status for select to authenticated using (auth.uid() = user_id);


-- Notifications Policies
create policy "Targeted Users can see notifications" on public.notifications for select to authenticated using (public.is_user_targeted_by_notification(id, organization_id));

-- Jobs
  -- Generate Bills for Subscriptions at the end of the month at 6:00 AM
  select cron.schedule('Generate Bills for Subscriptions at the end of the month at 6:00 AM', '0 1 1 * *', 'select public.generate_bill_for_subscriptions();');










-- Todo: Add the following to another migration file

-- Create a view to show the user's roles


-- /**
--  * REALTIME SUBSCRIPTIONS
--  * Only allow realtime listening on public tables.
--  */

-- begin; 
--   -- remove the realtime publication
--   drop publication if exists supabase_realtime; 

--   -- re-create the publication but don't enable it for any tables
--   create publication supabase_realtime;  
-- commit;

-- -- add tables to the publication
-- alter publication supabase_realtime add table public.organizations;
-- alter publication supabase_realtime add table public.courses;
-- alter publication supabase_realtime add table public.users;

-- /**
--  * HELPER FUNCTIONS
--  * Create test user helper method.
--  */
-- create or replace function public.create_user(
--     email text
-- ) returns uuid
--     security invoker
--     set search_path = auth
-- as $$
--   declare
--   user_id uuid;
-- begin
--   user_id := extensions.uuid_generate_v4();
  
--   insert into auth.users (id, email)
--     values (user_id, email)
--     returning id into user_id;

--     return user_id;
-- end;
-- $$ language plpgsql;


-- -- authorize with role-based access control (RBAC)
-- create function public.authorize(
--   requested_permission app_permission
-- )
-- returns boolean as $$
-- declare
--   bind_permissions int;
-- begin
--   select count(*)
--   from public.role_permissions
--   where role_permissions.permission = authorize.requested_permission
--     and role_permissions.role = (auth.jwt() ->> 'user_role')::public.app_role
--   into bind_permissions;
  
--   return bind_permissions > 0;
-- end;
-- $$ language plpgsql security invoker set search_path = public;

-- -- Secure the tables
-- alter table public.users enable row level security;
-- alter table public.organizations enable row level security;
-- alter table public.courses enable row level security;
-- alter table public.user_roles enable row level security;
-- alter table public.role_permissions enable row level security;
-- create policy "Allow logged-in read access" on public.users for select using ( auth.role() = 'authenticated' );
-- create policy "Allow individual insert access" on public.users for insert with check ( auth.uid() = id );
-- create policy "Allow individual update access" on public.users for update using ( auth.uid() = id );
-- create policy "Allow logged-in read access" on public.organizations for select using ( auth.role() = 'authenticated' );
-- create policy "Allow individual insert access" on public.organizations for insert with check ( auth.uid() = created_by );
-- create policy "Allow individual delete access" on public.organizations for delete using ( auth.uid() = created_by );
-- create policy "Allow authorized delete access" on public.organizations for delete using ( authorize('organizations.delete') );
-- create policy "Allow logged-in read access" on public.courses for select using ( auth.role() = 'authenticated' );
-- create policy "Allow individual insert access" on public.courses for insert with check ( auth.uid() = user_id );
-- create policy "Allow individual update access" on public.courses for update using ( auth.uid() = user_id );
-- create policy "Allow individual delete access" on public.courses for delete using ( auth.uid() = user_id );
-- create policy "Allow authorized delete access" on public.courses for delete using ( authorize('courses.delete') );
-- create policy "Allow individual read access" on public.user_roles for select using ( auth.uid() = user_id );

-- -- Send "previous data" on change 
-- alter table public.users replica identity full; 
-- alter table public.organizations replica identity full; 
-- alter table public.courses replica identity full;

-- -- inserts a row into public.users and assigns roles
