-- Custom Enums for Roles and Permissions
create type public.app_permission as enum (
  'users.read',
  'users.update',
  'users.delete'
);
create type public.app_role as enum ('owner','manager', 'teacher', 'student' );

-- ROLE PERMISSIONS
create table if not exists public.role_permissions (
  id           bigint generated by default as identity primary key,
  role         app_role not null,
  permission   app_permission not null,
  unique (role, permission)
);
comment on table public.role_permissions is 'Application permissions for each role.';
alter table public.role_permissions enable row level security;

-- Role Permissions Policies
create policy "everyone_can_read_role_permissions" on public.role_permissions for select to authenticated using (true);
